module.exports = {
    plugins: ["jest", "@angular-eslint/eslint-plugin"],
    settings: {
        jest: {
            version: 29,
        },
    },
    rules: {
        "@typescript-eslint/unbound-method": "off",
        "dot-notation": "off",
        "@typescript-eslint/dot-notation": [
            "error",
            {
                allowKeywords: true,
                allowIndexSignaturePropertyAccess: false,
                allowPrivateClassPropertyAccess: true,
                allowProtectedClassPropertyAccess: true,
            },
        ],
        "@typescript-eslint/no-extraneous-class": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@angular-eslint/component-class-suffix": "off",
        "@angular-eslint/use-component-selector": "off",
        
        "jest/consistent-test-it": "error",
        "jest/expect-expect": ["error", {
            "assertFunctionNames": ["expect", "expectObservable"],
        }],
        "jest/max-nested-describe": ["error", {
            "max": 5,
        }],
        "jest/prefer-lowercase-title": ["error", {
            "ignore": ["describe"]
        }],
        "jest/no-alias-methods": "error",
        "jest/no-conditional-expect": "error",
        "jest/no-conditional-in-test": "error",
        "jest/no-confusing-set-timeout": "error",
        "jest/no-deprecated-functions": "error",
        "jest/no-done-callback": "error",
        "jest/no-duplicate-hooks": "error",
        "jest/no-export": "error",
        "jest/no-focused-tests": "error",
        "jest/no-identical-title": "error",
        "jest/no-if": "error",
        "jest/no-interpolation-in-snapshots": "error",
        "jest/no-jasmine-globals": "error",
        "jest/no-large-snapshots": "error",
        "jest/no-mocks-import": "error",
        "jest/no-restricted-jest-methods": "error",
        "jest/no-restricted-matchers": "error",
        "jest/no-standalone-expect": "error",
        "jest/no-test-prefixes": "error",
        "jest/no-test-return-statement": "error",
        "jest/no-untyped-mock-factory": "error",
        "jest/prefer-each": "error",
        "jest/prefer-equality-matcher": "error",
        "jest/prefer-expect-resolves": "error",
        "jest/prefer-todo": "error",
        "jest/prefer-strict-equal": "error",
        "jest/prefer-to-be": "error",
        "jest/prefer-to-contain": "error",
        "jest/prefer-to-have-length": "error",
        "jest/require-to-throw-message": "error",
        "jest/require-top-level-describe": "error",
        "jest/valid-describe-callback": "error",
        "jest/valid-expect": "error",
        "jest/valid-expect-in-promise": "error",
        "jest/valid-title": "error",
        'jest/unbound-method': 'error',
        "jest/no-commented-out-tests": "error",
        "jest/no-disabled-tests": "error",
        "jest/prefer-spy-on": "error",
        "jest/prefer-comparison-matcher": "error",
        "jest/prefer-snapshot-hint": "error",
        "jest/prefer-mock-promise-shorthand": "error",
        
        "jest/max-expects": "off",
        "jest/no-hooks": "off",
        "jest/require-hook": "off",
        "jest/prefer-hooks-on-top": "off",
        "jest/prefer-hooks-in-order": "off",
        "jest/prefer-called-with": "off", 
        "jest/prefer-expect-assertions": "off",
    },
};
