module.exports = {
    plugins: ["@angular-eslint/template"],
    rules: {
        "@angular-eslint/template/accessibility-alt-text": "off",
        "@angular-eslint/template/accessibility-elements-content": "off",
        "@angular-eslint/template/accessibility-label-for": "off",
        "@angular-eslint/template/accessibility-label-has-associated-control": "off",
        "@angular-eslint/template/accessibility-table-scope": "off",
        "@angular-eslint/template/valid-aria": "error",
        "@angular-eslint/template/banana-in-box": "error",
        "@angular-eslint/template/click-events-have-key-events": "off",
        "@angular-eslint/template/conditional-complexity": "error",
        "@angular-eslint/template/cyclomatic-complexity": "off",
        "@angular-eslint/template/eqeqeq": "error",
        "@angular-eslint/template/i18n": "off",
        "@angular-eslint/template/mouse-events-have-key-events": "off",
        "@angular-eslint/template/no-any": "error",
        "@angular-eslint/template/no-autofocus": "error",
        "@angular-eslint/template/no-call-expression": "error",
        "@angular-eslint/template/no-distracting-elements": "error",
        "@angular-eslint/template/no-duplicate-attributes": "error",
        "@angular-eslint/template/no-negated-async": "error",
        "@angular-eslint/template/no-positive-tabindex": "error",
        "@angular-eslint/template/use-track-by-function": "off",
    },
};
